"""Lowering a crystal's symmetry on purpose, by dropping point operators.

The app finds the highest symmetry a structure has, which is what you want for
reading a file and for writing a small deck. It is not what you want when the
physics you are after is *forbidden* by that symmetry: a Jahn–Teller distortion,
a symmetry-breaking phonon, a spin arrangement that the full group averages
away. Those need the crystal declared in a lower group, so that atoms which the
full group makes equivalent can move apart.

Nothing here moves an atom. The structure, the cell and the coordinates stay
exactly as they are; what changes is how many of them are *independent*. A
reduction takes a space group of, say, 192 operations down to 32, which turns
one orbit of eight atoms into two orbits of four — and a geometry optimisation
that could only breathe can now distort.

**What can be removed.** Not any operator you like: what remains has to be a
group, closed under composition. Take the inversion out of m3̄m and 23 other
operators go with it — and there are two different maximal subgroups left
(432 and 4̄3m), which are different crystals. So the question a caller must ask
is not "remove this operator" but "which subgroup, of those that lack this
operator, do you want": :func:`subgroups_without` answers exactly that.

**Only point operators.** Removing a rotation while keeping every translation
gives a *translationengleiche* subgroup: same lattice, same cell, smaller point
group. Giving up translations instead (klassengleiche) multiplies the cell, and
that is what the supercell tools are for.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from functools import lru_cache
from itertools import combinations
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from crystalline.core.structure import Structure

# Two fractional coordinates closer than this are the same site.
_SITE_TOL = 1e-4

# How many generators a subgroup search combines. Every crystallographic point
# group is generated by at most three of its own elements, so three is complete
# rather than a guess — and at |G| <= 48 the search is still instant.
_MAX_GENERATORS = 3


@dataclass(frozen=True)
class Operator:
    """One point operator of the crystal, named the way the panel names it.

    ``rotation`` is the integer matrix in the conventional cell's own basis,
    which is how spglib gives it and how it must go back to spglib to be named.
    ``label`` is the crystallographic symbol with the direction it acts along —
    "4 ∥ [001]", "m ⊥ [110]", "1̄" — because "operator 17" is no use to anyone.
    """

    rotation: np.ndarray
    label: str
    noun: str = ""
    order: int = 1
    proper: bool = True

    @property
    def is_identity(self) -> bool:
        return bool(np.array_equal(self.rotation, np.eye(3, dtype=int)))

    def key(self) -> bytes:
        return self.rotation.astype(np.int8).tobytes()


@dataclass(frozen=True)
class Subgroup:
    """A symmetry the structure could be *declared* to have, instead of its own.

    ``sites`` is the size of the asymmetric unit under it — the number that says
    what the reduction buys, since it is exactly how many atoms become free to
    move independently.
    """

    rotations: Tuple[np.ndarray, ...]
    number: int
    symbol: str
    sites: int
    dropped: Tuple[str, ...] = ()
    # Whether declaring this group rebuilds the crystal we started from. False
    # means the subgroup is real but its standard setting is not the cell we
    # hold — a monoclinic unique axis, an origin choice — so a deck written
    # from it would describe a different crystal. See :func:`reproduces`.
    writable: bool = True

    @property
    def order(self) -> int:
        return len(self.rotations)

    def summary(self) -> str:
        lost = f", without {', '.join(self.dropped)}" if self.dropped else ""
        note = "" if self.writable else "  [needs a different cell setting]"
        return (f"{self.symbol} (No. {self.number}) — {self.order} point "
                f"operators, {self.sites} independent site"
                f"{'s' if self.sites != 1 else ''}{lost}{note}")


@dataclass(frozen=True)
class Symmetry:
    """The full symmetry of a structure, in the cell a deck would be written in.

    Built once by :func:`analyse` and passed around: every question below is
    asked of the same operator list, so the answers cannot disagree with each
    other or with what the panel is showing.
    """

    lattice: np.ndarray                 # conventional cell, rows are vectors
    positions: np.ndarray               # fractional, in that cell
    numbers: np.ndarray                 # atomic numbers, matching positions
    rotations: np.ndarray               # every space-group rotation (integers)
    translations: np.ndarray            # ...and its translation part
    operators: Tuple[Operator, ...]     # the distinct rotations, labelled
    number: int = 1
    symbol: str = "P1"

    def full(self) -> Subgroup:
        """The symmetry the structure actually has — the top of the tree."""
        return _subgroup(self, tuple(op.rotation for op in self.operators))


def analyse(structure: Structure, symprec: float = 1e-2) -> Optional[Symmetry]:
    """The structure's symmetry, in its conventional standard cell.

    ``None`` when there is no symmetry to reduce — a molecule, an empty
    structure, or a search that fails. A caller offering this feature should
    hide it rather than show an empty list.
    """
    if not _is_periodic(structure):
        return None
    try:
        import spglib

        lattice, positions, numbers = _conventional(structure, symprec)
        dataset = spglib.get_symmetry((lattice, positions, numbers), symprec=symprec)
        if dataset is None:
            return None
        rotations = np.asarray(dataset["rotations"], dtype=int)
        translations = np.asarray(dataset["translations"], dtype=float)
        kind = spglib.get_spacegroup_type_from_symmetry(
            rotations, translations, lattice, symprec=symprec)
    except Exception:  # noqa: BLE001 - no symmetry is a usable answer, a crash is not
        return None

    return Symmetry(
        lattice=lattice,
        positions=positions,
        numbers=numbers,
        rotations=rotations,
        translations=translations,
        operators=_label_operators(rotations, lattice),
        number=int(kind["number"]) if kind else 1,
        symbol=str(kind["international_short"]) if kind else "P1",
    )


def subgroups_without(symmetry: Symmetry, unwanted: Sequence[np.ndarray],
                      within: Optional[Sequence[np.ndarray]] = None) -> List[Subgroup]:
    """The largest subgroups that contain none of ``unwanted``.

    Usually one; sometimes two or three, and then they are genuinely different
    crystals and the caller has to choose. Empty when the operators asked about
    cannot all go — which happens only for the identity, since every subgroup
    contains it.

    ``within`` confines the search to subgroups of a group already descended to,
    which is what a second click means: having given up the inversion, the next
    operator dropped must leave something inside what is left, not somewhere
    else in the full group's tree.
    """
    banned = {_key(rotation) for rotation in unwanted}
    if not banned:
        return [symmetry.full() if within is None else descend(symmetry, within)]
    ceiling = (None if within is None
               else frozenset(_key(rotation) for rotation in within))
    candidates = [group for group in _all_subgroups(symmetry.operators)
                  if not (banned & group) and (ceiling is None or group <= ceiling)]
    if not candidates:
        return []
    largest = max(len(group) for group in candidates)
    lookup = {op.key(): op for op in symmetry.operators}
    best = [group for group in candidates if len(group) == largest]

    subgroups = []
    for group in sorted(best, key=lambda g: sorted(g)):
        kept = tuple(lookup[k].rotation for k in group)
        dropped = _dropped_labels(lookup, group)
        subgroups.append(_subgroup(symmetry, kept, dropped))
    return _distinct(subgroups)


def descend(symmetry: Symmetry, keep: Sequence[np.ndarray]) -> Subgroup:
    """Name and measure an explicit set of kept operators, closing it first.

    The closure matters: a caller that hands over a set which is not a group
    gets the group it generates, not a silent lie about what was asked for.
    """
    closed = _closure([np.asarray(r, dtype=int) for r in keep])
    lookup = {op.key(): op for op in symmetry.operators}
    kept = tuple(lookup[k].rotation for k in sorted(closed) if k in lookup)
    return _subgroup(symmetry, kept, _dropped_labels(lookup, closed))


def asymmetric_unit(symmetry: Symmetry, rotations: Sequence[np.ndarray]):
    """``(numbers, fractional coordinates)``: one representative site per orbit.

    The orbits are taken under the *space-group* operations whose rotation part
    survives — translations included, so a centred lattice still folds its
    copies together.
    """
    keep = {_key(rotation) for rotation in rotations}
    if keep <= {_key(np.eye(3, dtype=int))}:
        # No point symmetry left at all. The centring translations are still
        # there — the lattice keeps them — but a group named in a *primitive*
        # setting cannot be written against the conventional cell we are
        # holding. Every atom, in this cell, is the description that is both
        # true and writable, and it is what "no symmetry" means to a user.
        return symmetry.numbers, symmetry.positions
    mask = [index for index, rotation in enumerate(symmetry.rotations)
            if _key(rotation) in keep]
    positions = symmetry.positions
    seen = np.zeros(len(positions), dtype=bool)
    representatives: List[int] = []
    for index in range(len(positions)):
        if seen[index]:
            continue
        representatives.append(index)
        for op in mask:
            image = symmetry.rotations[op] @ positions[index] + symmetry.translations[op]
            delta = np.abs((positions - image + 0.5) % 1.0 - 0.5)
            hit = np.flatnonzero(
                (delta.max(axis=1) < _SITE_TOL)
                & (symmetry.numbers == symmetry.numbers[index]))
            seen[hit] = True
    return symmetry.numbers[representatives], positions[representatives]


def reproduces(symmetry: Symmetry, subgroup: Subgroup) -> bool:
    """Does declaring ``subgroup`` rebuild the crystal we started from?

    The group theory is exact; the *setting* is the risk. A subgroup's standard
    setting need not be the cell we are holding — a monoclinic unique axis or an
    origin choice can differ — and a deck written in the wrong setting is a
    plausible file describing another crystal. So the answer is checked the only
    way that cannot be fooled: build the crystal back from the number, the cell
    and the asymmetric unit, and see whether it is the one we had.
    """
    try:
        from pymatgen.core import Lattice
        from pymatgen.core import Structure as PmgStructure

        numbers, coords = asymmetric_unit(symmetry, subgroup.rotations)
        rebuilt = PmgStructure.from_spacegroup(
            subgroup.number, Lattice(symmetry.lattice),
            [int(z) for z in numbers], [list(c) for c in coords])
    except Exception:  # noqa: BLE001 - a group we cannot rebuild is one we will not write
        return False
    return _same_crystal(symmetry, rebuilt)


# ── the group theory ──────────────────────────────────────────────────────
def _closure(generators: Sequence[np.ndarray]) -> frozenset:
    """The set of matrices generated by these, as keys. Always has the identity."""
    identity = np.eye(3, dtype=int)
    seen = {_key(identity)}
    stack = [identity]
    while stack:
        current = stack.pop()
        for generator in generators:
            product = (current @ generator).astype(int)
            token = _key(product)
            if token not in seen:
                seen.add(token)
                stack.append(product)
    return frozenset(seen)


@lru_cache(maxsize=8)
def _subgroups_of(signature: Tuple[bytes, ...]) -> Tuple[frozenset, ...]:
    """Every subgroup of the point group, as sets of operator keys.

    By closing every set of up to three operators. Three is not a guess: no
    crystallographic point group needs more than three generators, so this
    enumerates all of them.

    Done on a multiplication table rather than on matrices. A cubic group needs
    eighteen thousand closures, and at a numpy matrix product each that is over
    two seconds — felt, on a tick box. Composing two operators is looking up one
    integer, so the whole search costs a few tens of milliseconds instead.
    """
    table = _multiplication_table(signature)
    count = len(signature)
    whole = frozenset(range(count))
    found = {whole}
    generated: Dict[Tuple[int, ...], frozenset] = {}
    for size in range(1, _MAX_GENERATORS + 1):
        for chosen in combinations(range(count), size):
            # A set that already generates everything cannot be extended into
            # anything smaller, so there is no point growing it.
            if size > 1 and generated.get(chosen[:-1]) == whole:
                continue
            closed = _closure_by_table(table, chosen)
            generated[chosen] = closed
            found.add(closed)
    return tuple(frozenset(signature[i] for i in group) for group in found)


def _multiplication_table(signature: Tuple[bytes, ...]) -> np.ndarray:
    """``table[i, j]`` is the index of operator i composed with operator j."""
    matrices = np.array([np.frombuffer(token, dtype=np.int8).astype(int).reshape(3, 3)
                         for token in signature])
    index = {token: i for i, token in enumerate(signature)}
    count = len(signature)
    table = np.empty((count, count), dtype=int)
    for i in range(count):
        products = matrices[i] @ matrices          # every product with one matmul
        for j, product in enumerate(products):
            table[i, j] = index[_key(product)]
    return table


def _closure_by_table(table: np.ndarray, generators: Sequence[int]) -> frozenset:
    """The subgroup generated by these operator indices, closed by lookup."""
    identity = next(i for i in range(len(table)) if table[i, i] == i and
                    all(table[i, j] == j for j in range(len(table))))
    seen = {identity}
    stack = [identity]
    while stack:
        current = stack.pop()
        for generator in generators:
            product = int(table[current, generator])
            if product not in seen:
                seen.add(product)
                stack.append(product)
    return frozenset(seen)


def _all_subgroups(operators: Sequence[Operator]) -> Tuple[frozenset, ...]:
    return _subgroups_of(tuple(op.key() for op in operators))


def _subgroup(symmetry: Symmetry, rotations: Tuple[np.ndarray, ...],
              dropped: Tuple[str, ...] = ()) -> Subgroup:
    number, symbol = _name(symmetry, rotations)
    numbers, _coords = asymmetric_unit(symmetry, rotations)
    subgroup = Subgroup(rotations=rotations, number=number, symbol=symbol,
                        sites=len(numbers), dropped=dropped)
    # Checked here, once, so nothing downstream can offer a group it cannot
    # write — the check is the whole defence against a plausible wrong deck.
    return replace(subgroup, writable=reproduces(symmetry, subgroup))


def _name(symmetry: Symmetry, rotations: Sequence[np.ndarray]) -> Tuple[int, str]:
    """The space-group type of the operations whose rotation part survives."""
    keep = {_key(rotation) for rotation in rotations}
    mask = [index for index, rotation in enumerate(symmetry.rotations)
            if _key(rotation) in keep]
    try:
        import spglib

        kind = spglib.get_spacegroup_type_from_symmetry(
            symmetry.rotations[mask], symmetry.translations[mask], symmetry.lattice)
        if kind:
            return int(kind["number"]), str(kind["international_short"])
    except Exception:  # noqa: BLE001 - an unnameable group is still a usable one
        pass
    return 1, "P1"


def _dropped_labels(lookup: Dict[bytes, Operator], kept: frozenset) -> Tuple[str, ...]:
    """What went, as distinct labels with a count — not one line per operator.

    A cubic group loses two dozen operators at a time, and most of them share a
    symbol: "3̄ ∥ [111] (×4)" is the sentence, "3̄, 3̄, 3̄, 3̄" is a stutter.
    """
    counts: Dict[str, int] = {}
    for token, operator in lookup.items():
        if token not in kept:
            counts[operator.label] = counts.get(operator.label, 0) + 1
    return tuple(label if count == 1 else f"{label} (×{count})"
                 for label, count in sorted(counts.items()))


def _distinct(subgroups: Sequence[Subgroup]) -> List[Subgroup]:
    """Drop repeats: two generator sets often close to the same group."""
    seen, unique = set(), []
    for subgroup in subgroups:
        token = frozenset(_key(rotation) for rotation in subgroup.rotations)
        if token not in seen:
            seen.add(token)
            unique.append(subgroup)
    return unique


# ── plumbing ──────────────────────────────────────────────────────────────
def _key(rotation) -> bytes:
    return np.asarray(rotation, dtype=int).astype(np.int8).tobytes()


def _is_periodic(structure: Structure) -> bool:
    """Three periodic directions — a crystal, not a slab, chain or molecule.

    A slab's symmetry is a *layer* group, and the space group this module would
    find for one is an answer about a lattice it does not have: the vacuum
    counted as a lattice vector. Worse, the deck writer ignores the result for a
    slab, so offering the choice at all was a control that did nothing. Slabs
    are :mod:`crystalline.core.slab_symmetry`'s business.
    """
    try:
        return (bool(structure.is_periodic) and len(structure) > 0
                and int(sum(bool(p) for p in structure.pbc)) == 3)
    except Exception:  # noqa: BLE001
        return False


def _conventional(structure: Structure, symprec: float):
    """The conventional standard cell — the one a ``.d12`` is written in."""
    from pymatgen.io.ase import AseAtomsAdaptor
    from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

    pmg = AseAtomsAdaptor().get_structure(structure.to_ase())
    conventional = SpacegroupAnalyzer(
        pmg, symprec=symprec).get_conventional_standard_structure()
    return (np.asarray(conventional.lattice.matrix, dtype=float),
            np.asarray(conventional.frac_coords, dtype=float) % 1.0,
            np.asarray([site.specie.Z for site in conventional], dtype=int))


def _label_operators(rotations: np.ndarray, lattice: np.ndarray) -> Tuple[Operator, ...]:
    """Name each distinct rotation, using the panel's own classifier.

    The classifier works in cartesian Å — the same frame the elements are drawn
    in — so the label beside a tick box is the label beside the axis in the 3D
    view, and no one has to work out which is which.
    """
    from crystalline.core import symmetry as symmetry_module

    basis = np.asarray(lattice, dtype=float).T
    inverse = np.linalg.inv(basis)
    operators: Dict[bytes, Operator] = {}
    for rotation in rotations:
        token = _key(rotation)
        if token in operators:
            continue
        cartesian = basis @ np.asarray(rotation, dtype=float) @ inverse
        element = symmetry_module._classify(cartesian, np.zeros(3), schoenflies=False)
        if element is None:                      # the identity classifies as nothing
            operators[token] = Operator(np.asarray(rotation, dtype=int), "1",
                                        "identity", 1, True)
            continue
        # _site_text is what puts "∥ [001]" on a panel row; without it every
        # 2-fold axis of a cubic crystal is a row reading "2".
        site = symmetry_module._site_text(element, lattice)
        operators[token] = Operator(
            rotation=np.asarray(rotation, dtype=int),
            label=f"{element.label} {site}".strip(),
            noun=element.noun,
            order=element.order,
            proper=element.proper,
        )
    return tuple(operators[key] for key in sorted(operators))


def _same_crystal(symmetry: Symmetry, rebuilt) -> bool:
    """Same atoms in the same places, however they are ordered."""
    if len(rebuilt) != len(symmetry.positions):
        return False
    wanted = sorted((int(z), *np.round(np.asarray(p) % 1.0, 4))
                    for z, p in zip(symmetry.numbers, symmetry.positions))
    got = sorted((int(site.specie.Z), *np.round(np.asarray(site.frac_coords) % 1.0, 4))
                 for site in rebuilt)
    for left, right in zip(wanted, got):
        if left[0] != right[0]:
            return False
        delta = np.abs((np.array(left[1:]) - np.array(right[1:]) + 0.5) % 1.0 - 0.5)
        if delta.max() > 1e-3:
            return False
    return True


__all__ = [
    "Operator",
    "Subgroup",
    "Symmetry",
    "analyse",
    "asymmetric_unit",
    "descend",
    "reproduces",
    "subgroups_without",
]
